from typing import Any

import numpy as np
import numpy.typing as npt

class BudgetExceeded(Exception): ...
def reduce_f2(
    offsets: npt.NDArray[np.int64], values: npt.NDArray[np.int64], evidence: str,
    max_columns: int, max_stored_entries: int, max_xor_steps: int,
    max_trace_entries: int, max_output_bytes: int,
) -> dict[str, Any]: ...

def assess_polygonal(
    vertices: npt.NDArray[np.float64], edges: npt.NDArray[np.int64],
    offsets: npt.NDArray[np.int64], coedges: npt.NDArray[np.int64], unit: str,
    max_input_bytes: int = ..., max_owned_bytes: int = ...,
    max_work_steps: int = ..., max_output_bytes: int = ...,
) -> dict[str, Any]: ...

class SurfaceLimits:
    def __init__(self, input_bytes: int, owned_bytes: int, work_steps: int, output_bytes: int) -> None: ...
class Surface:
    def arrays(self) -> dict[str, Any]: ...
class SurfaceOperators:
    def arrays(self) -> dict[str, Any]: ...
class AdmittedChart:
    def uv(self) -> npt.NDArray[np.float64]: ...
def prepare_surface(vertices: npt.NDArray[np.float64], edges: npt.NDArray[np.int64],
                    offsets: npt.NDArray[np.int64], coedges: npt.NDArray[np.int64],
                    unit: str, faces: npt.NDArray[np.int64], tolerance: float,
                    limits: SurfaceLimits) -> Surface: ...
def assemble_surface(surface: Surface, faces: npt.NDArray[np.int64],
                     weights: npt.NDArray[np.float64], limits: SurfaceLimits) -> SurfaceOperators: ...
def qualify_surface_chart(surface: Surface, uv: npt.NDArray[np.float64], orientation: int,
                          tolerance: float, limits: SurfaceLimits) -> dict[str, Any]: ...

class UVLimits:
    def __init__(self, input_bytes: int, owned_bytes: int, work_steps: int,
                 output_bytes: int, candidates: int) -> None: ...
class UVLocations:
    def arrays(self) -> dict[str, Any]: ...
class UVLocator:
    def usage(self) -> dict[str, int]: ...
    def locate(self, queries: npt.NDArray[np.float64], limits: UVLimits) -> UVLocations: ...
def prepare_uv_locator(chart: AdmittedChart, tolerance: float, agreement: float,
                       limits: UVLimits) -> UVLocator: ...

def realize_brep(nodes: Any, keys: Any, triangles: Any, faces: Any, segments: Any, uses: Any, face_count: int, vertex_count: int, tolerance: float, limits: SurfaceLimits) -> dict[str, Any]: ...

class QuadLimits:
    def __init__(self, owned_bytes: int, work_steps: int, output_bytes: int,
                 events: int, segments: int) -> None: ...
class QuadTraceResult:
    def arrays(self) -> dict[str, Any]: ...
class QuadPatch:
    def arrays(self) -> dict[str, Any]: ...
    def trace(self, seeds: npt.NDArray[np.int64], limits: QuadLimits) -> QuadTraceResult: ...
def prepare_quad_patch(vertices: npt.NDArray[np.float64], edges: npt.NDArray[np.int64],
                       offsets: npt.NDArray[np.int64], coedges: npt.NDArray[np.int64],
                       unit: str, input_bytes: int, owned_bytes: int, steps: int,
                       output_bytes: int) -> QuadPatch: ...
