"""Use only AFTER the custom component frontend has been built/installed.

The generated distribution imports its packaged MeshDiagnostics. Do not replace
that with an ordinary gr.HTML: it does not install the Svelte component protocol.
"""
import gradio as gr
from make_fixture import build
# Update this import to the package generated by your installed Gradio CLI.
from gradio_meshdiagnostics import MeshDiagnostics


def make_display_document():
    return build().model_dump(mode="json")


with gr.Blocks() as demo:
    gr.Markdown("### Mesh inspection — deterministic fixture")
    run = gr.Button("Load illustrative comparison")
    viewer = MeshDiagnostics()
    run.click(fn=make_display_document, inputs=[], outputs=[viewer])

if __name__ == "__main__":
    demo.launch()
