"""Copy into the backend package generated by your pinned Gradio component scaffold.

This source is NOT itself a prebuilt custom-component wheel with frontend assets.
"""
from __future__ import annotations
from collections.abc import Mapping
from typing import Any
from gradio.components.base import Component
from gradio.data_classes import GradioModel
from gradio.events import Events
from mesh_diagnostics import MeshPayload, adapt_legacy_payload


class GradioMeshPayload(MeshPayload, GradioModel):
    """Add Gradio's transport hooks without importing Gradio into the core schema."""


class MeshDiagnostics(Component):
    data_model = GradioMeshPayload
    EVENTS = [Events.select]

    def __init__(self, value: MeshPayload | dict[str, Any] | None = None, **kwargs: Any):
        kwargs.setdefault("interactive", False)
        super().__init__(value=value, **kwargs)

    def postprocess(self, value: MeshPayload | dict[str, Any] | None) -> GradioMeshPayload | None:
        """Validate/serialize only. No hidden mesh auditing, repair or file loading."""
        if value is None:
            return None
        if isinstance(value, MeshPayload):
            raw = value.model_dump()
        elif isinstance(value, Mapping):
            raw = dict(value)
            if "schema_version" not in raw:
                raw = adapt_legacy_payload(raw).model_dump()
        else:
            raise TypeError("MeshDiagnostics expects a prepared mesh payload; load NPZ explicitly in the pipeline")
        # Revalidate model instances too: Pydantic model fields can hold mutable lists.
        return GradioMeshPayload.model_validate(raw)

    def preprocess(self, payload: GradioMeshPayload | None) -> dict[str, Any] | None:
        """Return validated data only; NEVER treat client metric statuses as authority."""
        if payload is None:
            return None
        return GradioMeshPayload.model_validate(payload.model_dump()).model_dump()

    def example_payload(self) -> dict[str, Any]:
        return {
            "schema_version": "mesh-diagnostics/1", "mesh_id": "triangle-example",
            "geometry_revision": "example-v1", "diagnostic_revision": "example-audit-v1",
            "stage": "example", "units": "unspecified",
            "positions": [0., 0., 0., 1., 0., 0., 0., 1., 0.], "triangles": [0, 1, 2],
            "targets": [], "metrics": [], "notes": [], "triangle_parent_faces": None,
        }

    def example_value(self) -> dict[str, Any]:
        return self.example_payload()
